### ISSUE TITLE
add css and structure it

### ISSUE THREAD

**Issue by Arun0021** [Arun0021/Clock#1]
you can make it better 
#goodfirstissue
#firstcommit
helping newbies to learn git pull push merge etc.
best of luck

**Comment by Arun0021** [comment]
Hi

**Comment by Bashamega** [comment]
If you have a design you can send to me and I will finish it with a week

**Comment by Arun0021** [comment]
You can make one that suits the webpage motto

**Comment by Bashamega** [comment]
> You can make one that suits the webpage motto

ok

**Comment by Bashamega** [comment]
> > You can make one that suits the webpage motto
> 
> ok



> You can make one that suits the webpage motto

Please assign me

**Comment by Arun0021** [comment]
you can make similar to 
https://www.clocktab.com
just the clock not the additional facilities on the webpage
only the background and clock format

**Comment by Bashamega** [comment]
> you can make similar to https://www.clocktab.com just the clock not the additional facilities on the webpage only the background and clock format

How about this
![image](https://github.com/Arun0021/Clock/assets/110662505/7e51c3c3-c685-44ae-9404-37ab2f8b5af2)

**Comment by Arun0021** [comment]
Add a bg in outer div make it look aesthetic ✨️

**Comment by Bashamega** [comment]
> Add a bg in outer div make it look aesthetic ✨️

Sure.
Is this better
![image](https://github.com/Arun0021/Clock/assets/110662505/5cb0f3b8-a255-438a-95f2-25210ea820fb)

**Comment by Arun0021** [comment]
ya ok submit your code i am closing this issue soon
 best of luck
good work
